NLayerApp/NLayerApp.WEB/Controllers/ApartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NLayerApp.BusinessLogicLayer.Handler;
using NLayerApp.BusinessLogicLayer.Models;
using NLayerApp.DataAccessLayer.Interface;
using NLayerApp.DataAccessLayer.Repository;
using NLayerApp.WEB.Handler;

namespace NLayerApp.WEB.Controllers
{
    public class ApartmentController : Controller
    {
        IUnitOfWork unitOfWork=new UnitOfWork();

        // GET: Apartment
        [HttpGet]
        public ActionResult Index()
        {
            MySelect();
            ApartmentHandlerAllOutPut myOutPut=new ApartmentHandlerAllOutPut(unitOfWork);
            var result = myOutPut.GetAllApartment();
            return View(result);
        }

        //POST:Apartment
        [HttpPost]
        public ActionResult Index(ApartmentSearchParameters parameters)
        {
            MySelect();

            ApartmentHandlerOutPut myApartmentHandlerOutPut=new ApartmentHandlerOutPut(unitOfWork);
            var resultApartment = myApartmentHandlerOutPut.GetApartment(parameters);

            return View(resultApartment);
        }
        
        //Get Details Info
        [HttpGet]
        public ActionResult OutDetailsInfoApartment(int? id)
        {
            MySelect();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsInfoOutPutApartmentHandler myHandler = new DetailsInfoOutPutApartmentHandler(unitOfWork);
            var detailsInfo = myHandler.DetailsInfoObjectFind(id);

            if (detailsInfo==null)
            {
                return HttpNotFound();
            }
            return View(detailsInfo);

        }

        //Get Details Info by Id
        [HttpGet]
        public ActionResult IdOutPutDetailsInfoApartment(int? id)
        {
            MySelect();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsInfoOutPutApartmentHandler myHandler = new DetailsInfoOutPutApartmentHandler(unitOfWork);
            var idDetailsInfo = myHandler.IdInfoDetails(id);

            return View(idDetailsInfo);

        }

        void MySelect()
        {
            RegionHandler myRegionHandler=new RegionHandler(unitOfWork);
            var resultRegion = myRegionHandler.GetRegion();
            SelectList listRegion=new SelectList(resultRegion,"Id","Value");
            ViewBag.regionName = listRegion;

            VillageHandler myVillageHandler=new VillageHandler();
            var resultVillage = myVillageHandler.GetVillage();
            SelectList listVillage=new SelectList(resultVillage,"Id","Value");
            ViewBag.villageName = listVillage;
        }


    }
}

NLayerApp/NLayerApp.WEB/Controllers/CommercialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NLayerApp.BusinessLogicLayer.Handler;
using NLayerApp.BusinessLogicLayer.Models;
using NLayerApp.DataAccessLayer.Interface;
using NLayerApp.DataAccessLayer.Repository;
using NLayerApp.WEB.Handler;

namespace NLayerApp.WEB.Controllers
{
    public class CommercialController : Controller
    {
        IUnitOfWork unitOfWork=new UnitOfWork();

        // GET: Commercial
        [HttpGet]
        public ActionResult Index()
        {
            MySelect();
            CommercialHandlerAllOutPut myOutPut=new CommercialHandlerAllOutPut(unitOfWork);
            var result = myOutPut.GetAllCommercial();
            return View(result);
        }

        [HttpPost]
        public ActionResult Index(CommercialSearchParameters parameters)
        {
            MySelect();
            CommercialHandlerOutPut myCommercialHandlerOutPut=new CommercialHandlerOutPut(unitOfWork);
            var resultCommercial = myCommercialHandlerOutPut.GetCommercial(parameters);
            return View(resultCommercial);
        }

        [HttpGet]
        public ActionResult OutPutDetailsInfoCommercial(int? id)
        {
            MySelect();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsInfoOutPutCommercialHandler myHandler=new DetailsInfoOutPutCommercialHandler(unitOfWork);
            var detailsOutInfoCommercial = myHandler.DetailsInfoCommercialFind(id);
            if (detailsOutInfoCommercial == null)
            {
                return HttpNotFound();
            }
            return View(detailsOutInfoCommercial);
        }

        //Get Details info about object by Id
        [HttpGet]
        public ActionResult IdOutPutDetailsInfo(int? id)
        {
            MySelect();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsInfoOutPutCommercialHandler myHandler = new DetailsInfoOutPutCommercialHandler(unitOfWork);
            var idDetailsOutInfoCommercial = myHandler.IdOutPutDetailsInfo(id);
           
            return View(idDetailsOutInfoCommercial);
        }

        void MySelect()
        {
            RegionHandler myRegionHandler=new RegionHandler(unitOfWork);
            var resultRegion = myRegionHandler.GetRegion();
            SelectList listRegion=new SelectList(resultRegion,"Id","Value");
            ViewBag.regionName = listRegion;

            VillageHandler myVillageHandler=new VillageHandler(unitOfWork);
            var resultVillage = myVillageHandler.GetVillage();
            SelectList listVillage=new SelectList(resultVillage,"Id", "Value");
            ViewBag.villageName = listVillage;

           
        }
    }
}

NLayerApp/NLayerApp.WEB/Controllers/HouseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NLayerApp.BusinessLogicLayer.Handler;
using NLayerApp.BusinessLogicLayer.Models;
using NLayerApp.DataAccessLayer.Interface;
using NLayerApp.DataAccessLayer.Repository;
using NLayerApp.WEB.Handler;

namespace NLayerApp.WEB.Controllers
{
    public class HouseController : Controller
    {
        IUnitOfWork unitOfWork=new UnitOfWork();

        // GET: House
        [HttpGet]
        public ActionResult Index()
        {
            MySelect();
            HouseHandlerAllOutPut myOutPut=new HouseHandlerAllOutPut(unitOfWork);
            var result = myOutPut.GetAllHouse();
            return View(result);
        }


        //POST:House(form for search) 
        [HttpPost]
        public ActionResult Index(HouseSearchParameters parameters)
        {
            MySelect();
            HouseHandlerOutPut myHouseHandlerOutPut=new HouseHandlerOutPut(unitOfWork);
            var resultHouse = myHouseHandlerOutPut.GetHouse(parameters);

            return View(resultHouse);
        }

        //Get:House details Info
        [HttpGet]
        public ActionResult OutPutDetailsInfoHouse(int? id)
        {
            MySelect();
            if (id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsInfoOutPutHouseHandler myHandler=new DetailsInfoOutPutHouseHandler(unitOfWork);
            var detailsInfoHouse = myHandler.DetailsInfoHouseFind(id);
            if (detailsInfoHouse==null)
            {
                return HttpNotFound();
            }
            return View(detailsInfoHouse);

        }

        //Get details info about Land about Id 
        [HttpGet]
        public ActionResult IdOutPutDetaialsInfoHouse(int? id)
        {
            MySelect();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            DetailsInfoOutPutHouseHandler myHandler=new DetailsInfoOutPutHouseHandler(unitOfWork);
            var idDetailsInfo = myHandler.IdDetailsInfo(id);
            return View(idDetailsInfo);
        }

        void MySelect()
        {
            RegionHandler myRegionHandler=new RegionHandler(unitOfWork);
            var resultRegion = myRegionHandler.GetRegion();
            SelectList listRegion=new SelectList(resultRegion,"Id","Value");
            ViewBag.regionName = listRegion;

            VillageHandler myVillageHandler=new VillageHandler(unitOfWork);
            var resultVillage = myVillageHandler.GetVillage();
            SelectList listVillage=new SelectList(resultVillage, "Id", "Value");
            ViewBag.villageName = listVillage;
        }
    }
}

NLayerApp/NLayerApp.WEB/Controllers/LandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NLayerApp.BusinessLogicLayer.Handler;
using NLayerApp.BusinessLogicLayer.Models;
using NLayerApp.DataAccessLayer.Domains;
using NLayerApp.DataAccessLayer.Domains.Models;
using NLayerApp.DataAccessLayer.Interface;
using NLayerApp.DataAccessLayer.Repository;
using RegionHandler = NLayerApp.WEB.Handler.RegionHandler;
using VillageHandler = NLayerApp.WEB.Handler.VillageHandler;

namespace NLayerApp.WEB.Controllers
{
   
    public class LandController : Controller
    {
        
        IUnitOfWork unitOfWork=new UnitOfWork();

        // GET: Land
        [HttpGet]
        public ActionResult Index()
        {
           MySelect();
            LandHandlerAllOutPut myOutPut=new LandHandlerAllOutPut(unitOfWork);
            var result = myOutPut.GetAllInformation();
           return View(result);
        }
        
        //POST:Land 
        [HttpPost]
        public ActionResult Index(LandSearchParameters parameters)
        {
            MySelect();

            LandHandlerOutPut myLandHandlerOutPut = new LandHandlerOutPut(unitOfWork);

            var resultLand = myLandHandlerOutPut.GetInformation(parameters);
            return View(resultLand);
          
        }

        //Get details info about Land
        [HttpGet]
        public ActionResult OutPutDetailsInfoLand(int? id)
        {
            MySelect();
            if (id==null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsOutPutLandHandler myHandler=new DetailsOutPutLandHandler(unitOfWork);
            var detailsLandInfo = myHandler.DetailsInfoLandFind(id);
            if (detailsLandInfo == null)
            {
                return HttpNotFound();
            }
            return View(detailsLandInfo);
        }

        //Get details info about Land about Id 
        [HttpGet]
        public ActionResult IdOutPutDetaialsInfoLand(int ? id)
        {
            MySelect();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DetailsOutPutLandHandler myHandler = new DetailsOutPutLandHandler(unitOfWork);
            var detailsLandInfo = myHandler.IdDetailsInfo(id);
           
            return View(detailsLandInfo);
        }

        void MySelect()
        {
            RegionHandler myRegionHandler = new RegionHandler(unitOfWork);
            var resultRegion = myRegionHandler.GetRegion();
            SelectList listRegion = new SelectList(resultRegion, "Id", "Value");
            ViewBag.regionName = listRegion;

            VillageHandler myVillageHandler = new VillageHandler(unitOfWork);
            var resultVillage = myVillageHandler.GetVillage();
            SelectList listVillage = new SelectList(resultVillage, "Id", "Value");
            ViewBag.villageName = listVillage;

        }
    }
}

NLayerApp/NLayerApp.WEB/Views/Shared/_InputObjectForm.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />

    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@

</head>
<body>
            <!-- header page -->
            
                <header>
                    <h3>Адміністративна панель</h3>
                </header>
         
            <!-- end header page-->


            <!-- новигация  -->
            <nav id="nav">
                <ul>
                    <li>@Html.ActionLink("Головна", "Index", "Home")</li>
                    <li>@Html.ActionLink("Панель Адміністратора", "Index", "Administrator")</li>
                </ul>
            </nav>
            <!--end новигация -->

            <main id="main" role="main">

            
            @RenderBody()
            </main>



            <footer id="footer">
                <!-- иконки социальные сети  -->
                <article class="icons">
           
                </article>
                <!-- end социальные сети-->
            </footer>

</body>
</html>

NLayerApp/NLayerApp.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @*<link href="@Url.Content("~/Content/main.css")" rel="stylesheet" type="text/css" />*@

    @Styles.Render("~/Content/css")
    @Styles.Render("~/Font-awesome")

    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/menu.js")
    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>


</head>
<body>
    <div class="my_container">

        <!-- header page -->
        <header>
            <div class="my_row">
                <div class="my_cols my_col-3 logo">
                    <img src="/Image/small_logo.JPG">


                </div>
                <div class="my_cols my_col-6 logo_1">
                    <a id="touch-menu" class="mobile-menu" href="#"><span><i class="fa fa-align-justify"></i></span>меню</a>
                    <ul class="my-mobile-menu">
                        <li class="menu-text"><i class="icon-home"></i>@Html.ActionLink("головна", "Index", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("послуги", "Services", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("кредитування", "Kredit", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("контактна інформація", "MyContact", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("про нас", "MyAbout", "Home")</li>
                    </ul>
                    <img src="/Image/logo_z.jpg">
                </div>
                <div class="my_cols my_col-3 logo_2 header-image-bg">
                    <div class="new_logo">
                        <p>8(067)-473-11-45</p>
                    </div>
                </div>
            </div>
        </header>
        <!-- end header page-->
        <!-- новигация  -->
        <nav id="nav">
            <div class="my_row">
                <div class="my_cols my_col-12">
                    <ul class="menu">
                        <li class="menu-text">@Html.ActionLink("Головна", "Index", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Послуги", "Services", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Кредитування", "Kredit", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Контактна інформація", "MyContact", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Про Нас", "MyAbout", "Home")</li>
                    </ul>
                </div>
            </div>
        </nav>
        <!--end новигация -->
        <div class="my_row">

            <main id="main" role="main">
                <!--сайд бар рубрики -->
                <div class="my_cols my_col-3">
                    <details class="callMe">
                        <summary><span><i class="fa fa-align-justify"></i></span><span class="callMeText">Зателефонувати:</span></summary>
                            <ul class="callMeTel">
                                <li><a href="tel:+380674731145"> 0674731145</a></li>
                                <li><a href="tel:+380933342042"> 0933342042</a></li>
                                <li><a href="tel:+380679474897"> 0679474897</a></li>
                                <li><a href="tel:+380984971936"> 0984971936</a></li>
                            </ul>
                        
                    </details>
                    <aside id="sidebar">
                        <h2>Розділи:</h2>
                        <form method="GET" action="/SearchId/Index">

                            <input style="float: left; width: 11em; margin-left: 27px;" type="number" placeholder="код об'яви" name="id" />

                            <input style="float: right; height: 50px; margin-right:1em;" type="image" name="submit" src="../../Image/search.png" value="Пошук">

                        </form>
                        <ul>
                            <li class="stolb" style="clear: both;">@Html.ActionLink("Квартири", "Index", "Apartment")</li>
                            <li class="stolb"> @Html.ActionLink("Будинки", "Index", "House") </li>
                            <li class="stolb">@Html.ActionLink("Комерційна нерухомість", "Index", "Commercial") </li>
                            <li class="stolb"> @Html.ActionLink("Земельні ділянки", "Index", "Land")</li>
                        </ul>
                        <h2>Курси валют</h2>
                        <p>
                            <label class="valuta">$</label>
                            <input class="valuta" type="radio" value="dollar" checked="" name="valuta">
                            <a class="nevedimka" id="dollar" href="http://finance.i.ua/" target="_blank"><img src="http://f.i.ua/fp11_b15_c0_l1.png" border="0" alt="Курс долара"></a>
                            <label class="valuta">€</label>
                            <input class="valuta" type="radio" value="evro" name="valuta">
                            <a class="nevedimka" id="evro" href="http://finance.i.ua/" target="_blank"><img src="http://f.i.ua/fp13_b15_c2_l1.png" border="0" alt="Курс євро"></a>
                        </p>
                    </aside>
                </div>
                <div class="my_cols my_col-9 ">
                    <!--end сайд бар рубрика -->
                    @RenderBody()
                </div>
            </main>
        </div>
        <div class="my_row footer-bg footer-hg">

            <div class="my_cols my_col-12 footer-searchId">

              
                <!-- иконки социальные сети -->

                <a class="footer-icons" href="https://www.facebook.com/ANzatyshok/" target="_blank">
                    <img src="/Image/image_fb.jpg" alt="Ми на Facebook" />
                </a>
                <!-- end социальные сети-->

            </div>
        </div>
    </div>

</body>
</html>

NLayerApp/NLayerApp.WEB/Views/Shared/_SearchApartmentForm.cshtml
@using System.Web.UI.WebControls
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/menu.js")
    @Scripts.Render("~/Scripts/sliderText.js")

    <script defer src="https://use.fontawesome.com/releases/v5.0.10/js/all.js" integrity="sha384-slN8GvtUJGnv6ca26v8EzVaR9DC58QEwsIk9q1QXdCU8Yu8ck/tL/5szYlBbqmS+" crossorigin="anonymous"></script>

</head>
<body>
    <div class="my_container">
        <!-- header page -->
        <div class="my_row">
            <header>
                <div class="my_cols my_col-3 logo">
                    <img src="/Image/small_logo.JPG">
                </div>
                <div class="my_cols my_col-6 logo_1">
                    <a id="touch-menu" class="mobile-menu" href="#"><span><i class="fa fa-align-justify"></i></span>меню</a>
                    <ul class="my-mobile-menu">
                        <li class="menu-text"><i class="icon-home"></i>@Html.ActionLink("головна", "Index", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("послуги", "Services", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("кредитування", "Kredit", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("контактна інформація", "MyContact", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("про нас", "MyAbout", "Home")</li>
                    </ul>
                    <img src="/Image/logo_z.jpg">
                    <h2 class="front-sections">Квартири:</h2>
                </div>
                <div class="my_cols my_col-3 logo_2 header-searchApartment-bg">
                    <div class="new_logo">
                        <p>8(067)-473-11-45</p>
                    </div>
                </div>
            </header>
        </div>

        <!-- end header page-->
        <!-- новигация  -->
        <nav id="nav">

            <div class="my_row">
                <div class="my_cols my_col-12">
                    <ul class="menu">
                        <li class="menu-text">@Html.ActionLink("Головна", "Index", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Послуги", "Services", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Кредитування", "Kredit", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Контактна інформація", "MyContact", "Home")</li>
                        <li class="menu-text">@Html.ActionLink("Про Нас", "MyAbout", "Home")</li>
                    </ul>

                </div>
            </div>
        </nav>

        <!--end новигация -->
        <div class="my_row">
            <div class="my_row">
                <div class="my_cols my_col-12">
                    <details class="callMe">
                        <summary><span><i class="fa fa-align-justify"></i></span><span class="callMeText">Зателефонувати</span></summary>
                        <ul class="callMeTel">
                            <li><a href="tel:+380674731145"> 0674731145</a></li>
                            <li><a href="tel:+380933342042"> 0933342042</a></li>
                            <li><a href="tel:+380679474897"> 0679474897</a></li>
                            <li><a href="tel:+380984971936"> 0984971936</a></li>
                        </ul>
                    </details>
                </div>
            </div>

            <h2 class="sections">Квартири:</h2>
            <!-- форма выборки   -->
            <div class="my_row">
                <form method="POST" action="/Apartment/Index">
                    <div class="my_cols my_col-1">
                        <p class="searchText">
                            <b style="color: red">пошук :</b>
                        </p>
                    </div>
                    <div class="my_cols my_col-2">
                        <p class="mobSeachMenu-padding">
                            @Html.DropDownList("Region", ViewBag.regionName as SelectList, new { style = "height: 2.5em;" })
                        </p>
                    </div>
                    <div class="my_cols my_col-1">
                        <p class="mobSeachMenu-padding">
                            @Html.DropDownList("Village", ViewBag.villageName as SelectList, new { style = "height: 2.5em;" })
                        </p>
                    </div>
                    <div class="my_cols my_col-1">
                        <p class="mobSeachMenu-padding">
                            <select class="room_type" name="TypeRoom">
                                <option>тип кімнат</option>
                                <option value="окремі">окремі</option>
                                <option value="суміжні">суміжні</option>
                                <option value="комбіновані">комбіновані</option>
                            </select>
                        </p>
                    </div>
                    <div class="my_cols my_col-2">
                        <p class="mobSeachMenu-padding">
                            <select class="room_quantity" name="RoomsApartment">
                                <option value="">кількість кімнат</option>
                                <option value="1-но кімнатна">1 кімната</option>
                                <option value="2-во кімнатна">2 кімнати</option>
                                <option value="3-ри кімнатна">3 кімнати</option>
                                <option value="4-х кімнатна">4 кімнати</option>
                                <option value="5 кімат і більше">5 кімат і більше</option>
                            </select>
                        </p>
                    </div>

                    <div class="my_cols my_col-1">
                        <label>
                            <input type="radio" class="OperationType" name="OperationType" id="OperationType" checked value="продаж" aria-required="true" onchange="SelectedOperation(this)" /><span class="radioTypeText">продаж</span>
                        </label>
                    </div>
                    <div class="my_cols my_col-1">
                        <label>
                            <input type="radio" class="OperationType" value="оренда" name="OperationType" id="OperationType" aria-required="true" onchange="SelectedOperation(this)" /><span class="radioTypeText">оренда</span>
                        </label>
                    </div>
                    <div class="my_cols my_col-2">
                        <input style="display:inline-block;" class="nevedimkaRent" type="number" id="dol" min="500" max="1000000" placeholder="ціна в доларах" name="DollarCostTo" size="3">

                        <input class="nevedimkaRent" type="number" id="grn" min="500" max="70000" placeholder="ціна в гривні " name="GrnCostTo" size="3">
                    </div>


                    <div class="my_cols my_col-1">
                        <p>
                            <input class="mobileButtonSearch" type="submit" name="submit" value="пошук">
                        </p>
                        <p>
                            <input class="buttonSearch" type="image" name="submit" src="../../Image/search.png" value="Пошук">
                        </p>
                    </div>
                </form>
            </div>
            <div class="my_row">
                <div class="my_cols my_col-12">
                    @RenderBody()
                </div>
            </div>
            <!--end форма выборки   -->
        </div>
        <div class="my_row footer-bg footer-hg">

            <div class="my_cols my_col-12 footer-searchId">

                <form method="GET" action="/Apartment/IdOutPutDetailsInfoApartment">
                    код №
                    <input type="number" name="id" />
                    <input type="submit" value="пошук" />
                </form>
                <!-- иконки социальные сети -->

                @*<a class="footer-icons" href="https://www.facebook.com/ANzatyshok/" target="_blank">
                    <img src="/Image/image_fb.jpg" alt="Ми на Facebook" />
                </a>*@
                <!-- end социальные сети-->

            </div>
        </div>
    </div>  
</body>
</html>